### ISSUE TITLE
`classification.py` planning

### ISSUE THREAD

**Issue by aays** [ness-lab/recombinant-reads#16]
Notes from today's meeting about the script downstream of `filter` (formerly `phase_change_filter`/`phase_change_processing`) that takes filtered output and, for each read pair, attempts to:

- save relevant positional information (chromosome, read 1 start + end, read 2 start end)
- obtain/save variant information (list of tuples mentioned as possibility: e.g. `[(1, 1000), (1, 1050), (2, 1072)]`
  - will have to query VCF for this again, though speed is not as big a concern for this script
- use variant information to attempt to classify recombination event

The two 'easiest' recombination events to start with are:

1. crossovers (CO) - pattern should be 1s followed by 2s (or 2s followed by 1s) - e.g. a single phase change
2. noncrossover (aka gene conversion - NCO) - pattern involves two phase changes, e.g. 1s -> 2s -> 1s (or 2s -> 1s -> 2s)
  - NCOs are expected to be ~50-80 bp in C. reinhardtii - 100 bp might be a decent (arbitrary) cutoff

Anything not in these two categories is either a CO-GC (crossover associated gene conversion) or something fishy. 

This could be a custom read class, after which we'll be able to work with the bam record and this class in tandem:

```python
import pysam
from tqdm import tqdm

reader = pysam.AlignmentFile('fname.bam', 'r')
for read in tqdm(reader):
  read_data = ReadClass(read) # needs a better name lol
  event_type = read_data.call() 
  if event_type in ['NCO', 'CO']:
    # write `read` to out bam w/ pysam writer class
    # write read metadata to separate file? 
  else:
    # write `read` to other outfile - reads for review
    # honestly I think this should have metadata outfile as well, not sure
```

Once all the above functionality has been implemented, two extensions will involve:

1. Masking the ends of each read
2. Implementing a slightly different set of decisions to classify events based on that (will flesh out closer to then)

**Comment by aays** [comment]
It would also be neat if `read_data.call()` would also dynamically update an attribute (perhaps `read.event_type`?) of the object since that would help with debugging. Something like:

```python
class ReadClass():
  def __init__(self):
    # insert other attributes here
    self.event_type = self.call() # run when object is created
  
  def call(self):
    # insert code to use variant list to classify event
```

**Comment by jiyvliu** [comment]
Completed January 2021
