### ISSUE TITLE
Find way of representing haplotype phase of a read in a compact way

### ISSUE THREAD

**Issue by aays** [ness-lab/recombinant-reads#3]
This needs to be a way to succinctly represent the haplotype phase (i.e. to detect phase changes) for recombination event classification.

Things to think about:
1. How do we include length? (e.g. for putative gene conversions)
2. How do we account for PE reads? Do we store reads separately and link them, or combine info from both reads somehow?
3. How do we represent 'no-match' sites?

**Comment by jiyvliu** [comment]
From Tuesday 5/19 discussion:

This will most likely require a change of the cigar function (the one we've built) to pass back a list of tuples that include the haplotype and the location instead of just the haploytypes

**Comment by jiyvliu** [comment]
Data represented as class structures in Python, closed for now
